version: "3.8"

services:
  auth:
    container_name: auth
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "3050:80"
    networks:
      - ms_auth
  
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - .docker/postgress:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:"${DB_PASSWORD}"
      - POSTGRES_USER:"${DB_USERNAME}"
      - POSTGRES_DB:"${DB_DATABASE}"
    networks:
      - ms_auth

  web:
    container_name: web
    image: nginx:latest
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3040:80"
    networks:
      - ms_auth


volumes:
  postgress:
networks:
  ms_auth:
    driver: bridge